// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUpXPK7Nekn7wF6gvxAaqSG_THU-ekgxw',
    appId: '1:840420984500:web:2673c0c911b2ef5f8af9e1',
    messagingSenderId: '840420984500',
    projectId: 'school-manager-85296',
    authDomain: 'school-manager-85296.firebaseapp.com',
    storageBucket: 'school-manager-85296.firebasestorage.app',
    measurementId: 'G-VT4PV3X97E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTqTPnxJM3jGqnftqiHlMwYp5O-GU1K58',
    appId: '1:840420984500:android:28d467dd15bd83bf8af9e1',
    messagingSenderId: '840420984500',
    projectId: 'school-manager-85296',
    storageBucket: 'school-manager-85296.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQJED6McXJZzz1WyaYkcGFx4VqdksY1Rg',
    appId: '1:840420984500:ios:dc26b953e11fc1738af9e1',
    messagingSenderId: '840420984500',
    projectId: 'school-manager-85296',
    storageBucket: 'school-manager-85296.firebasestorage.app',
    iosBundleId: 'com.example.schoolManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQJED6McXJZzz1WyaYkcGFx4VqdksY1Rg',
    appId: '1:840420984500:ios:dc26b953e11fc1738af9e1',
    messagingSenderId: '840420984500',
    projectId: 'school-manager-85296',
    storageBucket: 'school-manager-85296.firebasestorage.app',
    iosBundleId: 'com.example.schoolManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUpXPK7Nekn7wF6gvxAaqSG_THU-ekgxw',
    appId: '1:840420984500:web:195499e40c208d4d8af9e1',
    messagingSenderId: '840420984500',
    projectId: 'school-manager-85296',
    authDomain: 'school-manager-85296.firebaseapp.com',
    storageBucket: 'school-manager-85296.firebasestorage.app',
    measurementId: 'G-6PYHQDESRP',
  );
}
